### ISSUE TITLE
Container wont start

### ISSUE THREAD

**Issue by mmanningcp** [yukaia/Checkpoint-Skyline-Compose#1]
Hey ya,
Trying to troubleshot this but having issues any ideas? 

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/sysadmin/docker/grafana-prometheus/prometheus/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /home/sysadmin/docker/grafana-prometheus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by yukaia** [comment]
@mmanningcp At first glance I'm going to guess it's related to trying to run it from the home directory. 

I'll see if I can duplicate this issue when I get some free time, in the mean time I'd try cloning the project to /opt and trying it there. 

I'm curious, are there any other docker containers running on this host, specifically prometheus? I've realized that the container name I used is just plain "prometheus" when I should be using something like "prometheus-skyline" to prevent any potential issues with other prometheus containers that might be running on the host.

**Comment by yukaia** [comment]
I went ahead and updated the docker-compose-sample.yml's container names to *-skyline for each container. Pull down the changes and see if that helps.

**Comment by mmanningcp** [comment]
Same issues if I run it from Home or opt

 ⠼ Container prometheus-skyline  Starting                                                                                                                                        0.4s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/opt/skyline/prometheus/prometheus.yml" to rootfs at "/etc/prometheus/prometheus.yml": mount /opt/skyline/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by yukaia** [comment]
Yeah, I wonder if there's a container name or volume conflict.

Try that update I made to the compose file and let me know what happens.

**Comment by yukaia** [comment]
@mmanningcp would it also be possible for you to provide a sanitized version of your docker-compose.yml?
